const DATA = window.CVLEO_DATA || {};
const publications = DATA.publications || [];
const experience = DATA.experience || { professional: [], research: [], academic: [] };
const events = DATA.events || { stays: [], congresses: [] };
const awards = DATA.awards || [];
const testimonials = DATA.testimonials || [];
const projects = DATA.projects || { featured: [], previous: [] };

if (!DATA.publications) console.warn('CVLEO_DATA.publications was not loaded. Check assets/data/publications.js path and GitHub upload.');

const state = { page: 1, perPage: 3, search: '', type: 'all', year: 'all', featured: 'all' };
const moreState = { professional: false, research: false, academic: false, events: false, awards: false };

let testimonialIndex = 0;

function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

function sortedPublications(items){return [...items].sort((a,b)=>(b.year-a.year)||Number(b.featured)-Number(a.featured)||a.title.localeCompare(b.title));}

function authorLine(authors){const visible=authors.slice(0,3).map(a=>a.includes('Ledesma')?`<span class="me">${escapeHtml(a)}</span>`:escapeHtml(a)).join(' · ');if(authors.length<=3)return visible;const hidden=authors.slice(3).map(a=>a.includes('Ledesma')?`<span class="me">${escapeHtml(a)}</span>`:escapeHtml(a)).join(' · ');return `${visible} <button class="more-authors" data-more>+${authors.length-3} authors⌄</button><span class="hidden extra-authors"> · ${hidden}</span>`;}

function pubCard(p){const cls=p.type.includes('Book')?'book':p.type.includes('Conference')?'conference':'journal';const icon=cls==='book'?'BK':cls==='conference'?'CP':'JA';const links=Object.entries(p.links||{}).filter(([,v])=>v&&v!=='#').map(([k,v])=>`<a href="${v}" target="_blank" rel="noopener">${k}</a>`).join('');return `<article class="publication-card ${cls} hover-card ${p.featured?'featured':''}"><div class="pub-icon">${icon}</div><div class="pub-main"><div class="pub-meta"><span class="date">${p.year}</span><span class="type ${cls}">${p.type}</span>${p.featured?'<span class="star" title="Featured publication">★</span>':''}</div><h3>${escapeHtml(p.title)}</h3><p class="journal-name">${escapeHtml(p.venue)}</p><p class="authors">${authorLine(p.authors)}</p><div class="chips">${p.tags.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><div class="pub-links">${links}</div></div><aside class="pub-side"><div class="pub-badges"><span>${p.quartile||'Published'}</span><span>${escapeHtml(p.area||'')}</span></div><div class="citation-box"><div><strong>${p.wos}</strong><span>WoS</span></div><div><strong>${p.scopus}</strong><span>Scopus</span></div></div></aside></article>`;}

function filtered(){return sortedPublications(publications.filter(p=>{const text=JSON.stringify(p).toLowerCase();const featuredOk=state.featured==='all'||state.featured==='featured'&&p.featured||state.featured==='regular'&&!p.featured;return(state.type==='all'||p.type===state.type)&&(state.year==='all'||String(p.year)===state.year)&&featuredOk&&text.includes(state.search.toLowerCase());}));}

function paginate(items){return items.slice((state.page-1)*state.perPage,state.page*state.perPage);}

function renderChart(items){const types=['Journal Article','Book Chapter','Conference Proceeding'];const clsMap={'Journal Article':'journal','Book Chapter':'book','Conference Proceeding':'conference'};const years=[...new Set(items.map(p=>p.year))].sort();const totals=years.map(y=>items.filter(p=>p.year===y).length);const max=Math.max(1,...totals);const bars=years.map((y,yi)=>{let offset=0;const segments=types.map(t=>{const count=items.filter(p=>p.year===y&&p.type===t).length;if(!count)return'';const h=count/max*120;const seg=`<button type="button" class="chart-segment ${clsMap[t]}" data-chart-year="${y}" data-chart-type="${t}" title="${y} · ${t}: ${count}" style="height:${h}px;bottom:${offset}px"><span>${count}</span></button>`;offset+=h;return seg;}).join('');return `<div class="chart-column"><div class="chart-stack">${segments}</div><button type="button" class="chart-year-label" data-chart-year="${y}">${y}<br><strong>${totals[yi]}</strong></button></div>`;}).join('');document.getElementById('publication-chart').innerHTML=`<div class="chart-title">Publications by year and type <span class="chart-subtitle">click a bar segment or year to filter</span></div><div class="chart-combo no-line"><div class="chart-bars">${bars}</div></div>`;}

function renderPublications(){const items=filtered();document.getElementById('publication-count').textContent=`${items.length} published records found. Showing 3 per page.`;renderChart(items);document.getElementById('all-publication-list').innerHTML=paginate(items).map(pubCard).join('');const pages=Math.max(1,Math.ceil(items.length/state.perPage));if(state.page>pages)state.page=pages;const pager=document.getElementById('all-pager');pager.innerHTML='';for(let i=1;i<=pages;i++){const b=document.createElement('button');b.textContent=i;b.className=i===state.page?'active':'';b.onclick=()=>{state.page=i;renderPublications();};pager.appendChild(b);}}

function initYearFilter(){const yearSelect=document.getElementById('publication-year');if(!yearSelect)return;const years=[...new Set(publications.map(p=>p.year))].sort((a,b)=>b-a);years.forEach(y=>{const option=document.createElement('option');option.value=String(y);option.textContent=y;yearSelect.appendChild(option);});}

function renderExperience(){Object.entries(experience).forEach(([key,items])=>{const el=document.getElementById(`${key}-list`);if(!el)return;const groups=[];items.forEach((x,i)=>{const orgKey=x[4]||x[2]||`item-${i}`;const orgData=(DATA.organizations||{})[orgKey]||{};let g=groups.find(v=>v.key===orgKey);if(!g){g={key:orgKey,name:orgData.name||x[2]||'',logo:orgData.logo||'',items:[]};groups.push(g);}g.items.push({...x,index:i});});el.innerHTML=groups.map(g=>`<article class="institution-card hover-card"><div class="institution-logo">${g.logo?`<img src="${escapeHtml(g.logo)}" alt="${escapeHtml(g.name)} logo" loading="lazy">`:escapeHtml(g.name.slice(0,3).toUpperCase())}</div><div class="institution-body"><h3>${escapeHtml(g.name)}</h3><div class="institution-timeline">${g.items.map(x=>`<div class="institution-role ${x.index>2&&!moreState[key]?'hidden-extra':''}"><span class="date">${escapeHtml(x[0])}</span><h4>${escapeHtml(x[1])}</h4><p><strong>${escapeHtml(x[2])}</strong></p><p>${escapeHtml(x[3])}</p></div>`).join('')}</div></div></article>`).join('');const btn=document.querySelector(`[data-show-more="${key}"]`);if(btn){btn.style.display=items.length>3?'inline-flex':'none';btn.textContent=moreState[key]?'Show less':'See more...';}});}

function flagClass(code){return `flag-svg flag-${code}`;}

function renderEvents(){const el=document.getElementById('event-list');if(!el)return;el.innerHTML=events.map((e,i)=>`<article class="event-card hover-card ${i>3&&!moreState.events?'hidden-extra':''}"><span class="${flagClass(e[0])}"></span><h3>${escapeHtml(e[1])}</h3><p>${escapeHtml(e[2])}</p><div class="chips"><span>${escapeHtml(e[3])}</span></div></article>`).join('');const btn=document.querySelector('[data-show-more="events"]');if(btn){btn.style.display=events.length>4?'inline-flex':'none';btn.textContent=moreState.events?'Show less':'See more...';}}

function renderAwards(){const el=document.getElementById('award-list');if(!el)return;el.innerHTML=awards.map((a,i)=>`<article class="experience-card hover-card ${i>3&&!moreState.awards?'award-hidden':''}"><span class="date">${escapeHtml(a[0])}</span><h3>${escapeHtml(a[1])}</h3><p>${escapeHtml(a[2])}</p></article>`).join('');const btn=document.querySelector('[data-show-more="awards"]');if(btn){btn.style.display=awards.length>4?'inline-flex':'none';btn.textContent=moreState.awards?'Show less':'See more...';}}

function safeImageTag(src,alt,fallback=''){const onError=fallback?` onerror="this.onerror=null;this.src='${escapeHtml(fallback)}';"`:'';return `<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}" loading="lazy"${onError}>`;}

function renderProjects(){const featuredEl=document.getElementById('featured-project-list');const previousEl=document.getElementById('previous-project-list');if(featuredEl){featuredEl.innerHTML=(projects.featured||[]).map(p=>`<article class="project-card featured-project-card hover-card">${safeImageTag(p.image,p.title,p.fallbackImage||'')}<div><div class="project-topline"><span class="date">${escapeHtml(p.period||'Featured')}</span>${p.status?`<span class="construction-badge">${escapeHtml(p.status)}</span>`:''}</div><h3>${escapeHtml(p.title)}</h3>${p.subtitle?`<p>${escapeHtml(p.subtitle)}</p>`:''}<div class="chips project-keywords">${(p.keywords||[]).map(k=>`<span>${escapeHtml(k)}</span>`).join('')}</div>${p.url?`<a class="btn small project-btn" href="${escapeHtml(p.url)}" target="_blank" rel="noopener">${escapeHtml(p.linkLabel||'Visit website')}</a>`:''}</div></article>`).join('');}if(previousEl){previousEl.innerHTML=(projects.previous||[]).map(p=>`<article class="project-card previous-project-card hover-card">${safeImageTag(p.image,p.title,p.fallbackImage||'')}<div><h3>${escapeHtml(p.title)}</h3>${p.description?`<p>${escapeHtml(p.description)}</p>`:''}${p.url?`<a class="text-link" href="${escapeHtml(p.url)}" target="_blank" rel="noopener">Open project →</a>`:''}</div></article>`).join('');}}

function initShowMore(){document.querySelectorAll('[data-show-more]').forEach(btn=>{btn.addEventListener('click',()=>{const key=btn.dataset.showMore;moreState[key]=!moreState[key];if(key==='events')renderEvents();else if(key==='awards')renderAwards();else renderExperience();});});}

function initTabs(){document.querySelectorAll('.tabs').forEach(group=>{group.addEventListener('click',e=>{const btn=e.target.closest('.tab');if(!btn)return;const id=btn.dataset.tab;group.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const parent=group.parentElement;parent.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));const panel=parent.querySelector('#'+id);if(panel)panel.classList.add('active');});});}

function initExperienceTabs(){document.querySelectorAll('.exp-tab').forEach(btn=>{btn.addEventListener('click',()=>{const key=btn.dataset.exp;document.querySelectorAll('.exp-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.experience-panel').forEach(p=>p.classList.remove('active'));document.getElementById(`${key}-panel`).classList.add('active');});});}

function initNav(){const links=[...document.querySelectorAll('.nav-link')];const sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+entry.target.id));}})},{rootMargin:'-20% 0px -70% 0px'});sections.forEach(s=>obs.observe(s));const mobile=document.querySelector('.mobile-nav-toggle');if(mobile)mobile.onclick=()=>document.querySelector('.sidebar').classList.toggle('open');links.forEach(a=>a.onclick=()=>document.querySelector('.sidebar').classList.remove('open'));const collapse=document.querySelector('.sidebar-collapse');if(collapse){collapse.addEventListener('click',()=>{document.body.classList.toggle('sidebar-collapsed');collapse.textContent=document.body.classList.contains('sidebar-collapsed')?'›':'‹';});}}

function initTestimonials(){const windowEl=document.querySelector('.testimonial-window');const dots=document.getElementById('testimonial-dots');const wrap=document.querySelector('.testimonial-carousel');if(!windowEl||!dots||!Array.isArray(testimonials)||!testimonials.length)return;windowEl.innerHTML=testimonials.map((t,i)=>`<article class="testimonial-card ${i===0?'active':''}">${t.photo?`<img class="testimonial-photo" src="${escapeHtml(t.photo)}" alt="${escapeHtml(t.name)}" loading="lazy" />`:'<div class="photo-placeholder">◌</div>'}<p>“${escapeHtml(t.text)}”</p><h3>${escapeHtml(t.name)}</h3>${t.role?`<small class="testimonial-role">${escapeHtml(t.role)}</small>`:""}${t.company?`<small class="testimonial-company">${escapeHtml(t.company)}</small>`:""}</article>`).join('');dots.innerHTML='';const cards=[...windowEl.querySelectorAll('.testimonial-card')];function show(i){testimonialIndex=(i+cards.length)%cards.length;cards.forEach((c,idx)=>c.classList.toggle('active',idx===testimonialIndex));dots.querySelectorAll('button').forEach((d,idx)=>d.classList.toggle('active',idx===testimonialIndex));}cards.forEach((_,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Go to testimonial ${i+1}`);b.onclick=()=>show(i);dots.appendChild(b);});const prev=document.getElementById('testimonial-prev');const next=document.getElementById('testimonial-next');if(prev)prev.onclick=()=>show(testimonialIndex-1);if(next)next.onclick=()=>show(testimonialIndex+1);show(0);let timer=setInterval(()=>show(testimonialIndex+1),10000);if(wrap){wrap.addEventListener('mouseenter',()=>clearInterval(timer));wrap.addEventListener('mouseleave',()=>{timer=setInterval(()=>show(testimonialIndex+1),10000);});}}

document.addEventListener('click',e=>{if(e.target.matches('[data-more]')){const extra=e.target.nextElementSibling;extra.classList.toggle('hidden');e.target.textContent=extra.classList.contains('hidden')?e.target.textContent.replace('⌃','⌄'):e.target.textContent.replace('⌄','⌃');}if(e.target.matches('[data-toggle="inventors"]'))document.getElementById('inventors').classList.toggle('hidden');});

function initPublicationFilters(){initYearFilter();[['publication-search','input','search'],['publication-type','change','type'],['publication-year','change','year'],['publication-featured','change','featured']].forEach(([id,evt,key])=>{const el=document.getElementById(id);if(el)el.addEventListener(evt,e=>{state[key]=e.target.value;state.page=1;renderPublications();});});const chart=document.getElementById('publication-chart');if(chart){chart.addEventListener('click',e=>{e.preventDefault();const year=e.target.closest('[data-chart-year]')?.dataset.chartYear;const type=e.target.closest('[data-chart-type]')?.dataset.chartType;if(!year&&!type)return;if(year){state.year=state.year===year?'all':year;const y=document.getElementById('publication-year');if(y)y.value=state.year;}if(type){state.type=state.type===type?'all':type;const t=document.getElementById('publication-type');if(t)t.value=state.type;}state.page=1;renderPublications();});}}

initTabs();
initExperienceTabs();
initNav();
initPublicationFilters();
renderPublications();
renderProjects();
renderExperience();
renderEvents();
renderAwards();
initShowMore();
initTestimonials();
